name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master

jobs:
  build:
    strategy:

      # ATTENTION: the list of architectures must be in sync with helpers/build-release-binaries/main.go!
      matrix:
        # run cross-compile in two batches parallel so the overall tests run faster
        targets:
          - "linux/386 linux/amd64 linux/arm linux/arm64"
          - "darwin/amd64 darwin/arm64 windows/386 windows/amd64"

    env:
      go: 1.16.x
      GOPROXY: https://proxy.golang.org

    runs-on: ubuntu-latest

    name: Cross Compile for ${{ matrix.targets }}

    steps:
      - name: Set up Go ${{ env.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install gox
        run: |
          go get github.com/mitchellh/gox

      - name: Cross-compile with gox for ${{ matrix.targets }}
        env:
          GOFLAGS: "-trimpath"
          GOX_ARCHS: "${{ matrix.targets }}"
        run: |
          mkdir build-output
          gox -parallel 2 -verbose -osarch "$GOX_ARCHS" -output "build-output/{{.Dir}}_{{.OS}}_{{.Arch}}" ./cmd/restic
          gox -parallel 2 -verbose -osarch "$GOX_ARCHS" -tags debug -output "build-output/{{.Dir}}_{{.OS}}_{{.Arch}}_debug" ./cmd/restic


  lint:
    name: lint
    runs-on: ubuntu-latest
    env:
      go: 1.16.x
    steps:
      - name: Set up Go ${{ env.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.36
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
          args: --verbose --timeout 5m
          skip-go-installation: true

        # only run golangci-lint for pull requests, otherwise ALL hints get
        # reported. We need to slowly address all issues until we can enable
        # linting the master branch :)
        if: github.event_name == 'pull_request'

      - name: Check go.mod/go.sum
        run: |
          echo "check if go.mod and go.sum are up to date"
          go mod tidy
          git diff --exit-code go.mod go.sum
