name: Release

on:
  push:
    tags:
      - "*.*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build Release Binaries
        run: |
          # build binaries
          make build

      - name: Publish image into GitHub Container Registry
        env:
          REGISTRY: ghcr.io/stashed
          USERNAME: 1gtm
          DOCKER_TOKEN: ${{ secrets.LGTM_GITHUB_TOKEN }}
        run: |
          # login into the registry
          docker login ghcr.io --username ${USERNAME} --password ${DOCKER_TOKEN}
          # build and push the docker image
          make push

      - name: Publish image into DockerHub
        env:
          REGISTRY: stashed
          USERNAME: 1gtm
          DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          # login into the registry
          docker login --username ${USERNAME} --password ${DOCKER_TOKEN}
          # build and push the docker image
          make push

      - name: Build Changelog
        id: changelog-builder
        uses: mikepenz/release-changelog-builder-action@v2.1.0
        with:
          configuration: .github/changelog-config.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fail_on_unmatched_files: true
          body:  ${{steps.changelog-builder.outputs.changelog}}
          files: $(pwd)/.go/bin/restic*
